version: 1.0

data_sources:
  - name: financial_reports
    type: volume
    catalog: field_ai_examples
    schema: alphaleger
    volume_name: financebench
    path: pdf
    format: pdf

processing_steps:
  - name: parsing
    function: ai_cookbook.functions.parsing.extract_text_from_pdf  # Full module path to the function
    inputs:
      - financial_reports
    output_table: processed_data.extracted_texts

  - name: chunking
    function: ai_cookbook.functions.chunking.chunk_text  # Full module path to the function
    inputs:
      - parsing
    output_table: processed_data.enriched_texts

outputs:
  - name: financial_reports_index
    type: vector_index
    inputs: 
      - chunking
    embedding_model: openai-embedding-model
    output_table: main_catalog.sec_rag.financial_reports_index
