version: 1.0

data_sources:
  - name: financial_reports
    type: volume
    path: /Volumes/main/raw_data/financial_reports
    format: pdf
    catalog: main
    schema: agent_app
    volume_name: raw_data

processing_steps:
  - name: parsing
    function: ai_cookbook.functions.parsing.extract_text_from_pdf  # Full module path to the function
    inputs:
      - financial_reports
    output_table: processed_data.extracted_texts

  - name: add_metadata
    function: ai_cookbook.functions.metadata.add_metadata  # Full module path to the function
    inputs:
      - parsing
      - financial_reports
    output_table: processed_data.enriched_texts

outputs:
  - name: financial_reports_index
    type: vector_index
    inputs: 
      - add_metadata
    embedding_model: openai-embedding-model
    output_table: main_catalog.sec_rag.financial_reports_index
